[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.7.0-dev.2"

[target.riscv32im-unknown-none-elf.dependencies]
risc0-zkvm-guest = "0.7.0-dev.2"
